create extension if not exists pgcrypto;

create table if not exists public.clients(id uuid primary key default gen_random_uuid(),name text not null,phone text,email text,company text,location text,notes text,created_at timestamptz not null default now());
create table if not exists public.service_packages(id uuid primary key default gen_random_uuid(),service_name text not null,package_name text not null,price numeric(12,2) not null default 0,labor_cost numeric(12,2) not null default 0,active boolean not null default true,created_at timestamptz not null default now(),unique(service_name,package_name));
create table if not exists public.quotes(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,customer_name text not null,phone text,location text,service_name text not null,package_name text not null,package_price numeric(12,2) not null default 0,one_way_km numeric(10,2) not null default 0,travel_price numeric(12,2) not null default 0,extras_total numeric(12,2) not null default 0,final_price numeric(12,2) not null default 0,vehicle_cost numeric(12,2) not null default 0,labor_cost numeric(12,2) not null default 0,equipment_cost numeric(12,2) not null default 600,other_cost numeric(12,2) not null default 0,estimated_profit numeric(12,2) not null default 0,deposit_amount numeric(12,2) not null default 0,remaining_amount numeric(12,2) not null default 0,status text not null default 'taslak' check(status in('taslak','gonderildi','kabul','reddedildi','iptal')),notes text,created_at timestamptz not null default now());
create table if not exists public.jobs(id uuid primary key default gen_random_uuid(),quote_id uuid references public.quotes(id) on delete set null,client_id uuid references public.clients(id) on delete set null,customer_name text not null,phone text,location text,service_name text not null,package_name text,scheduled_at timestamptz not null,delivery_at timestamptz,total_price numeric(12,2) not null default 0,deposit_amount numeric(12,2) not null default 0,paid_amount numeric(12,2) not null default 0,remaining_amount numeric(12,2) not null default 0,payment_status text not null default 'bekliyor' check(payment_status in('bekliyor','kismi','odendi','iade')),job_status text not null default 'planlandi' check(job_status in('planlandi','cekim_tamamlandi','kurguda','teslime_hazir','teslim_edildi','iptal')),notes text,created_at timestamptz not null default now());
create table if not exists public.tasks(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,job_id uuid references public.jobs(id) on delete set null,title text not null,task_type text not null default 'diger' check(task_type in('cekim','teslim','arama','revizyon','odeme','qr_menu','diger')),due_at timestamptz not null,status text not null default 'bekliyor' check(status in('bekliyor','tamamlandi','iptal')),priority text not null default 'normal' check(priority in('dusuk','normal','yuksek','acil')),completed_at timestamptz,notes text,created_at timestamptz not null default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),job_id uuid references public.jobs(id) on delete cascade,quote_id uuid references public.quotes(id) on delete set null,amount numeric(12,2) not null check(amount>=0),payment_type text not null default 'diger' check(payment_type in('kapora','kalan','diger','iade')),payment_method text,paid_at timestamptz not null default now(),notes text,created_at timestamptz not null default now());
create table if not exists public.expenses(id uuid primary key default gen_random_uuid(),job_id uuid references public.jobs(id) on delete set null,title text not null,amount numeric(12,2) not null check(amount>=0),expense_date date not null default current_date,notes text,created_at timestamptz not null default now());
create table if not exists public.job_history(id uuid primary key default gen_random_uuid(),job_id uuid not null references public.jobs(id) on delete cascade,from_status text,to_status text not null,note text,changed_at timestamptz not null default now());

create table if not exists public.qr_menus(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,business_name text not null,slug text not null unique check(slug~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),package_name text not null check(package_name in('Start','Pro','Premium')),product_limit integer,update_allowance integer,updates_used integer not null default 0,renewal_price numeric(12,2) not null default 0,starts_at date not null default current_date,renews_at date not null default ((current_date+interval '1 year')::date),status text not null default 'taslak' check(status in('taslak','yayinda','pasif')),logo_url text,primary_color text,wifi_name text,wifi_password text,instagram text,whatsapp text,address text,created_at timestamptz not null default now(),template_name text not null default 'minimal' check(template_name in('minimal','luks','modern','dogal')),secondary_color text,background_color text not null default '#ffffff',cover_url text,phone text,maps_url text,working_hours text,currency text not null default 'TRY',language_options text[] not null default array['tr'],show_wifi boolean not null default true,show_instagram boolean not null default true,show_whatsapp boolean not null default true,show_address boolean not null default true,published_at timestamptz,updated_at timestamptz not null default now());
create table if not exists public.menu_categories(id uuid primary key default gen_random_uuid(),menu_id uuid not null references public.qr_menus(id) on delete cascade,name text not null,sort_order integer not null default 0,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.menu_products(id uuid primary key default gen_random_uuid(),menu_id uuid not null references public.qr_menus(id) on delete cascade,category_id uuid references public.menu_categories(id) on delete set null,name text not null,description text,price numeric(12,2) not null default 0,image_url text,sort_order integer not null default 0,active boolean not null default true,sold_out boolean not null default false,badges text[] not null default '{}',allergens text[] not null default '{}',created_at timestamptz not null default now());
create table if not exists public.qr_menu_updates(id uuid primary key default gen_random_uuid(),qr_menu_id uuid not null references public.qr_menus(id) on delete cascade,update_type text not null default 'icerik',description text,counts_against_allowance boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.menu_views(id bigint generated by default as identity primary key,menu_id uuid not null references public.qr_menus(id) on delete cascade,viewed_at timestamptz not null default now(),referrer text);
create table if not exists public.qr_renewals(id uuid primary key default gen_random_uuid(),qr_menu_id uuid not null references public.qr_menus(id) on delete cascade,amount numeric(12,2) not null check(amount>=0),payment_method text,period_start date not null,period_end date not null,paid_at timestamptz not null default now(),notes text,created_at timestamptz not null default now());
create table if not exists public.app_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());

alter table public.clients enable row level security;alter table public.service_packages enable row level security;alter table public.quotes enable row level security;alter table public.jobs enable row level security;alter table public.tasks enable row level security;alter table public.payments enable row level security;alter table public.expenses enable row level security;alter table public.job_history enable row level security;alter table public.qr_menus enable row level security;alter table public.menu_categories enable row level security;alter table public.menu_products enable row level security;alter table public.qr_menu_updates enable row level security;alter table public.menu_views enable row level security;alter table public.qr_renewals enable row level security;alter table public.app_settings enable row level security;

insert into public.app_settings(key,value) values('pricing','{"free_one_way_km":20,"customer_extra_roundtrip_km_price":18,"vehicle_roundtrip_km_cost":12,"equipment_cost":600,"deposit_rate":0.3}'::jsonb),('qr_packages','{"Start":{"product_limit":40},"Pro":{"product_limit":100},"Premium":{"product_limit":null}}'::jsonb) on conflict(key) do nothing;
insert into public.service_packages(service_name,package_name,price,labor_cost) values('Drone Çekimi','Başlangıç',0,0),('Drone Çekimi','Premium',0,0),('Düğün & Nişan','Başlangıç',0,0),('Düğün & Nişan','Premium',0,0),('Emlak & Gayrimenkul','Başlangıç',0,0),('Emlak & Gayrimenkul','Premium',0,0),('Mekân & İşletme','Başlangıç',0,0),('Mekân & İşletme','Premium',0,0),('Organizasyon','Başlangıç',0,0),('Organizasyon','Premium',0,0),('Reklam & Tanıtım','Başlangıç',0,0),('Reklam & Tanıtım','Premium',0,0) on conflict(service_name,package_name) do nothing;

create index if not exists tasks_due_status_idx on public.tasks(status,due_at);create index if not exists jobs_schedule_status_idx on public.jobs(job_status,scheduled_at);create index if not exists qr_menus_renew_idx on public.qr_menus(status,renews_at);create index if not exists menu_categories_menu_sort_idx on public.menu_categories(menu_id,sort_order);create index if not exists menu_products_menu_category_sort_idx on public.menu_products(menu_id,category_id,sort_order);create index if not exists qr_renewals_menu_paid_idx on public.qr_renewals(qr_menu_id,paid_at desc);
