'use server';
import{revalidatePath}from'next/cache';import{redirect}from'next/navigation';import{createAdminSession,credentialsMatch,requireAdmin}from'./auth';import{insert,select,update}from'./db';import{calculateQuote}from'./pricing';import type{Job,Quote,ServicePackage}from'./types';
const text=(f:FormData,k:string)=>String(f.get(k)??'').trim(),num=(f:FormData,k:string)=>Number(f.get(k)??0)||0;
export async function loginAction(f:FormData){if(!credentialsMatch(text(f,'email'),text(f,'password')))redirect('/admin/login?hata=1');await createAdminSession();redirect('/admin')}
export async function createClientAction(f:FormData){await requireAdmin();await insert('clients',{name:text(f,'name'),phone:text(f,'phone')||null,email:text(f,'email')||null,company:text(f,'company')||null,location:text(f,'location')||null,notes:text(f,'notes')||null});revalidatePath('/admin/musteriler')}
export async function createQuoteAction(f:FormData){await requireAdmin();const p=(await select<ServicePackage>('service_packages',`id=eq.${encodeURIComponent(text(f,'package_id'))}&select=*`))[0];if(!p)throw new Error('Paket bulunamadı.');const oneWayKm=num(f,'one_way_km'),extrasTotal=num(f,'extras_total'),otherCost=num(f,'other_cost'),c=calculateQuote({packagePrice:Number(p.price),oneWayKm,extrasTotal,laborCost:Number(p.labor_cost),otherCost});await insert('quotes',{customer_name:text(f,'customer_name'),phone:text(f,'phone')||null,location:text(f,'location')||null,service_name:p.service_name,package_name:p.package_name,package_price:p.price,one_way_km:oneWayKm,travel_price:c.travelPrice,extras_total:extrasTotal,final_price:c.finalPrice,vehicle_cost:c.vehicleCost,labor_cost:p.labor_cost,equipment_cost:600,other_cost:otherCost,estimated_profit:c.estimatedProfit,deposit_amount:c.depositAmount,remaining_amount:c.remainingAmount,status:'taslak',notes:text(f,'notes')||null});revalidatePath('/admin/teklif')}
export async function acceptQuoteAction(f:FormData){await requireAdmin();const id=text(f,'id'),q=(await select<Quote>('quotes',`id=eq.${encodeURIComponent(id)}&select=*`))[0];if(!q)throw new Error('Teklif bulunamadı.');await update('quotes',`id=eq.${encodeURIComponent(id)}`,{status:'kabul'});const job=await insert<Job>('jobs',{quote_id:q.id,customer_name:q.customer_name,phone:q.phone,location:q.location,service_name:q.service_name,package_name:q.package_name,scheduled_at:text(f,'scheduled_at'),delivery_at:text(f,'delivery_at')||null,total_price:q.final_price,deposit_amount:q.deposit_amount,paid_amount:0,remaining_amount:q.final_price,payment_status:'bekliyor',job_status:'planlandi',notes:q.notes});await insert('job_history',{job_id:job.id,from_status:null,to_status:'planlandi',note:'Tekliften işe dönüştürüldü.'});await insert('tasks',{job_id:job.id,title:`${q.customer_name} · Çekim`,task_type:'cekim',due_at:text(f,'scheduled_at'),priority:'yuksek'});const delivery=text(f,'delivery_at');if(delivery)await insert('tasks',{job_id:job.id,title:`${q.customer_name} · Teslim`,task_type:'teslim',due_at:delivery,priority:'yuksek'});revalidatePath('/admin');revalidatePath('/admin/agenda');revalidatePath('/admin/isler')}
export async function updateJobAction(f:FormData){await requireAdmin();const id=text(f,'id'),old=(await select<Job>('jobs',`id=eq.${encodeURIComponent(id)}&select=*`))[0];if(!old)throw new Error('İş bulunamadı.');const total=num(f,'total_price'),paid=num(f,'paid_amount'),next=text(f,'job_status'),delivery=text(f,'delivery_at')||null;await update('jobs',`id=eq.${encodeURIComponent(id)}`,{job_status:next,payment_status:paid>=total?'odendi':paid>0?'kismi':'bekliyor',paid_amount:paid,remaining_amount:Math.max(0,total-paid),delivery_at:delivery});if(old.job_status!==next)await insert('job_history',{job_id:id,from_status:old.job_status,to_status:next,note:null});revalidatePath('/admin');revalidatePath('/admin/agenda');revalidatePath('/admin/isler');revalidatePath('/admin/finans')}
export async function createTaskAction(f:FormData){await requireAdmin();await insert('tasks',{title:text(f,'title'),task_type:text(f,'task_type')||'diger',due_at:text(f,'due_at'),priority:text(f,'priority')||'normal',notes:text(f,'notes')||null,job_id:text(f,'job_id')||null});revalidatePath('/admin');revalidatePath('/admin/agenda')}
export async function completeTaskAction(f:FormData){await requireAdmin();await update('tasks',`id=eq.${encodeURIComponent(text(f,'id'))}`,{status:'tamamlandi',completed_at:new Date().toISOString()});revalidatePath('/admin');revalidatePath('/admin/agenda')}
export async function addPaymentAction(f:FormData){await requireAdmin();const jobId=text(f,'job_id'),amount=num(f,'amount'),job=(await select<Job>('jobs',`id=eq.${encodeURIComponent(jobId)}&select=*`))[0];if(!job||amount<=0)throw new Error('Ödeme bilgisi geçersiz.');await insert('payments',{job_id:job.id,quote_id:job.quote_id,amount,payment_type:text(f,'payment_type')||'diger',payment_method:text(f,'payment_method')||null,notes:text(f,'notes')||null});const paid=Number(job.paid_amount)+amount,total=Number(job.total_price);await update('jobs',`id=eq.${encodeURIComponent(job.id)}`,{paid_amount:paid,remaining_amount:Math.max(0,total-paid),payment_status:paid>=total?'odendi':'kismi'});revalidatePath('/admin');revalidatePath('/admin/isler');revalidatePath('/admin/finans')}
function slugify(v:string){return v.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
export async function createQrMenuAction(f:FormData){await requireAdmin();const businessName=text(f,'business_name'),pkg=text(f,'package_name')as'Start'|'Pro'|'Premium',presets={Start:{limit:40,updates:4},Pro:{limit:100,updates:12},Premium:{limit:null,updates:null}},p=presets[pkg]??presets.Start,s=new Date(),r=new Date(s);r.setFullYear(r.getFullYear()+1);await insert('qr_menus',{business_name:businessName,slug:slugify(text(f,'slug')||businessName),package_name:pkg,product_limit:p.limit,update_allowance:p.updates,updates_used:0,renewal_price:num(f,'renewal_price'),starts_at:s.toISOString().slice(0,10),renews_at:r.toISOString().slice(0,10),status:'taslak',primary_color:text(f,'primary_color')||'#171717',wifi_name:text(f,'wifi_name')||null,wifi_password:text(f,'wifi_password')||null,instagram:text(f,'instagram')||null,whatsapp:text(f,'whatsapp')||null,address:text(f,'address')||null});revalidatePath('/admin/qr-menu')}
