'use server';
import{revalidatePath}from'next/cache';import{redirect}from'next/navigation';import{requireAdmin}from'./auth';import{insert,select,update}from'./db';import{getAgencyProjects,getCustomerPages,type AgencyProject,type AgencyProjectStatus,type CustomerPageRecord}from'./agency-projects';
const text=(f:FormData,k:string)=>String(f.get(k)??'').trim();const num=(f:FormData,k:string)=>Number(text(f,k)||0);const nullable=(v:string)=>v||null;type Setting<T>={key:string;value:T};
async function save<T>(key:string,value:T){const exists=(await select<Setting<T>>('app_settings',`key=eq.${encodeURIComponent(key)}&select=key&limit=1`))[0];if(exists)await update('app_settings',`key=eq.${encodeURIComponent(key)}`,{value,updated_at:new Date().toISOString()});else await insert('app_settings',{key,value})}
function refresh(){revalidatePath('/admin');revalidatePath('/admin/projeler');revalidatePath('/admin/musteri-sayfalari');revalidatePath('/admin/musteriler')}
export async function createAgencyProjectAction(f:FormData){await requireAdmin();const brand=text(f,'brand_name'),name=text(f,'project_name');if(!brand||!name)throw new Error('Marka ve proje adı gerekli.');const now=new Date().toISOString(),rows=await getAgencyProjects();rows.push({id:crypto.randomUUID(),client_id:nullable(text(f,'client_id')),brand_name:brand,project_name:name,project_type:text(f,'project_type')||'Web Projesi',domain:nullable(text(f,'domain')),live_url:nullable(text(f,'live_url')),admin_url:nullable(text(f,'admin_url')),github_url:nullable(text(f,'github_url')),vercel_url:nullable(text(f,'vercel_url')),supabase_url:nullable(text(f,'supabase_url')),price:num(f,'price'),paid:num(f,'paid'),start_date:nullable(text(f,'start_date')),delivery_date:nullable(text(f,'delivery_date')),status:(text(f,'status')||'planlandi')as AgencyProjectStatus,maintenance_date:nullable(text(f,'maintenance_date')),notes:nullable(text(f,'notes')),created_at:now,updated_at:now});await save('agency_projects',rows);refresh();redirect('/admin/projeler')}
export async function updateAgencyProjectAction(f:FormData){await requireAdmin();const id=text(f,'id'),rows=await getAgencyProjects(),i=rows.findIndex(x=>x.id===id);if(i<0)throw new Error('Proje bulunamadı.');rows[i]={...rows[i],client_id:nullable(text(f,'client_id')),brand_name:text(f,'brand_name'),project_name:text(f,'project_name'),project_type:text(f,'project_type'),domain:nullable(text(f,'domain')),live_url:nullable(text(f,'live_url')),admin_url:nullable(text(f,'admin_url')),github_url:nullable(text(f,'github_url')),vercel_url:nullable(text(f,'vercel_url')),supabase_url:nullable(text(f,'supabase_url')),price:num(f,'price'),paid:num(f,'paid'),start_date:nullable(text(f,'start_date')),delivery_date:nullable(text(f,'delivery_date')),status:text(f,'status')as AgencyProjectStatus,maintenance_date:nullable(text(f,'maintenance_date')),notes:nullable(text(f,'notes')),updated_at:new Date().toISOString()};await save('agency_projects',rows);refresh()}
export async function deleteAgencyProjectAction(f:FormData){await requireAdmin();const id=text(f,'id'),rows=(await getAgencyProjects()).filter(x=>x.id!==id);await save('agency_projects',rows);refresh();redirect('/admin/projeler')}
export async function createCustomerPageAction(f:FormData){await requireAdmin();const brand=text(f,'brand_name');if(!brand)throw new Error('Marka adı gerekli.');const now=new Date().toISOString(),rows=await getCustomerPages();rows.push({id:crypto.randomUUID(),client_id:nullable(text(f,'client_id')),brand_name:brand,page_type:(text(f,'page_type')||'tesekkur_degerlendirme')as CustomerPageRecord['page_type'],page_url:nullable(text(f,'page_url')),price:num(f,'price'),paid:num(f,'paid'),created_date:nullable(text(f,'created_date')),delivery_date:nullable(text(f,'delivery_date')),status:(text(f,'status')||'hazirlaniyor')as CustomerPageRecord['status'],instagram:nullable(text(f,'instagram')),trendyol:nullable(text(f,'trendyol')),website:nullable(text(f,'website')),whatsapp:nullable(text(f,'whatsapp')),review_url:nullable(text(f,'review_url')),notes:nullable(text(f,'notes')),created_at:now,updated_at:now});await save('customer_pages',rows);refresh();redirect('/admin/musteri-sayfalari')}
export async function updateCustomerPageAction(f:FormData){await requireAdmin();const id=text(f,'id'),rows=await getCustomerPages(),i=rows.findIndex(x=>x.id===id);if(i<0)throw new Error('Müşteri sayfası bulunamadı.');rows[i]={...rows[i],client_id:nullable(text(f,'client_id')),brand_name:text(f,'brand_name'),page_type:text(f,'page_type')as CustomerPageRecord['page_type'],page_url:nullable(text(f,'page_url')),price:num(f,'price'),paid:num(f,'paid'),created_date:nullable(text(f,'created_date')),delivery_date:nullable(text(f,'delivery_date')),status:text(f,'status')as CustomerPageRecord['status'],instagram:nullable(text(f,'instagram')),trendyol:nullable(text(f,'trendyol')),website:nullable(text(f,'website')),whatsapp:nullable(text(f,'whatsapp')),review_url:nullable(text(f,'review_url')),notes:nullable(text(f,'notes')),updated_at:new Date().toISOString()};await save('customer_pages',rows);refresh()}
export async function deleteCustomerPageAction(f:FormData){await requireAdmin();const id=text(f,'id'),rows=(await getCustomerPages()).filter(x=>x.id!==id);await save('customer_pages',rows);refresh();redirect('/admin/musteri-sayfalari')}
