import{cookies}from'next/headers';import{createHmac,timingSafeEqual}from'node:crypto';import{redirect}from'next/navigation';import{select}from'./db';
const COOKIE='omra_admin_session',TTL=43200;
function secret(){const v=process.env.ADMIN_SESSION_SECRET;if(!v||v.length<32)throw new Error('ADMIN_SESSION_SECRET eksik.');return v}
function supabaseConfig(){const url=(process.env.NEXT_PUBLIC_SUPABASE_URL??process.env.SUPABASE_URL??'').replace(/\/$/,''),key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'';if(!url||!key)throw new Error('Supabase Auth ayarları eksik.');return{url,key}}
function sign(p:string){return createHmac('sha256',secret()).update(p).digest('hex')}
function sessionPayload(userId:string){const ts=String(Math.floor(Date.now()/1000)),raw=`${userId}.${ts}`;return`${raw}.${sign(raw)}`}
async function readSession(){const token=(await cookies()).get(COOKIE)?.value;if(!token)return null;const parts=token.split('.');if(parts.length!==3)return null;const[userId,ts,sig]=parts,raw=`${userId}.${ts}`,expected=sign(raw),a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return null;const age=Math.floor(Date.now()/1000)-Number(ts);if(!Number.isFinite(age)||age<0||age>TTL)return null;return{userId}}
export async function authenticateAdmin(email:string,password:string){const{url,key}=supabaseConfig();const r=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email:email.trim().toLowerCase(),password}),cache:'no-store'});if(!r.ok)return null;const data=await r.json()as{user?:{id?:string}};const userId=data.user?.id;if(!userId)return null;const profile=(await select<{user_id:string;role:string;active:boolean}>('admin_profiles',`user_id=eq.${encodeURIComponent(userId)}&active=eq.true&select=user_id,role,active&limit=1`))[0];if(!profile||!['owner','admin','staff'].includes(profile.role))return null;return profile}
export async function createAdminSession(userId:string){const s=await cookies();s.set(COOKIE,sessionPayload(userId),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:TTL})}
export async function clearAdminSession(){const s=await cookies();s.set(COOKIE,'',{path:'/',maxAge:0})}
export async function isAdminAuthenticated(){const session=await readSession();if(!session)return false;const profile=(await select<{user_id:string;role:string;active:boolean}>('admin_profiles',`user_id=eq.${encodeURIComponent(session.userId)}&active=eq.true&select=user_id,role,active&limit=1`))[0];return!!profile&&['owner','admin','staff'].includes(profile.role)}
export async function requireAdmin(){if(!(await isAdminAuthenticated()))redirect('/admin/login')}
