'use server';
import{revalidatePath}from'next/cache';import{redirect}from'next/navigation';import{requireAdmin}from'./auth';import{insert,remove,select,update}from'./db';import{uploadDigitalBrandLogo}from'./storage';
const text=(f:FormData,k:string)=>String(f.get(k)??'').trim();const yes=(f:FormData,k:string)=>f.get(k)==='on';
function slugify(v:string){return v.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
async function refresh(id?:string,slug?:string){revalidatePath('/admin/dijital-markalar');if(id)revalidatePath(`/admin/dijital-markalar/${id}`);if(slug)revalidatePath(`/dijital/${slug}`)}
export async function createDigitalBrandAction(f:FormData){await requireAdmin();const name=text(f,'name'),slug=slugify(text(f,'slug')||name),title=text(f,'title')||`${name} resmi bağlantıları`,qrName=text(f,'qr_name')||name;if(!name||!slug)throw new Error('Marka adı ve geçerli sayfa adresi gerekli.');const exists=await select<{id:string}>('digital_brand_pages',`slug=eq.${encodeURIComponent(slug)}&select=id&limit=1`);if(exists.length)throw new Error('Bu sayfa adresi kullanımda.');const row=await insert<{id:string}>('digital_brand_pages',{name,slug,eyebrow:text(f,'eyebrow')||name,title,description:text(f,'description')||'',accent:text(f,'accent')||'#171717',accent_soft:text(f,'accent_soft')||'rgba(23,23,23,.10)',footer_note:text(f,'footer_note')||`© ${name}`,qr_name:qrName,status:'taslak'});await refresh(row.id,slug);redirect(`/admin/dijital-markalar/${row.id}`)}
export async function updateDigitalBrandAction(f:FormData){await requireAdmin();const id=text(f,'id'),name=text(f,'name'),slug=slugify(text(f,'slug')||name),status=text(f,'status');if(!id||!name||!slug)throw new Error('Marka bilgileri eksik.');if(!['taslak','yayinda','pasif'].includes(status))throw new Error('Geçersiz durum.');const current=(await select<{slug:string;logo_url:string|null}>('digital_brand_pages',`id=eq.${encodeURIComponent(id)}&select=slug,logo_url&limit=1`))[0];if(!current)throw new Error('Marka sayfası bulunamadı.');if(current.slug==='yuun'&&slug!=='yuun')throw new Error('YUUN sayfasının QR adresi sabittir.');const collision=await select<{id:string}>('digital_brand_pages',`slug=eq.${encodeURIComponent(slug)}&id=neq.${encodeURIComponent(id)}&select=id&limit=1`);if(collision.length)throw new Error('Bu sayfa adresi kullanımda.');let logoUrl=text(f,'logo_url')||current.logo_url;const file=f.get('logo_file');if(file instanceof File&&file.size>0)logoUrl=await uploadDigitalBrandLogo(file,id);await update('digital_brand_pages',`id=eq.${encodeURIComponent(id)}`,{name,slug,eyebrow:text(f,'eyebrow')||name,title:text(f,'title'),description:text(f,'description'),accent:text(f,'accent')||'#171717',accent_soft:text(f,'accent_soft')||'rgba(23,23,23,.10)',logo_url:logoUrl||null,footer_note:text(f,'footer_note')||null,qr_name:text(f,'qr_name')||name,status,updated_at:new Date().toISOString()});await refresh(id,current.slug);await refresh(id,slug)}
export async function deleteDigitalBrandAction(f:FormData){await requireAdmin();const id=text(f,'id'),row=(await select<{slug:string}>('digital_brand_pages',`id=eq.${encodeURIComponent(id)}&select=slug&limit=1`))[0];if(!row)throw new Error('Silinecek marka bulunamadı.');await remove('digital_brand_pages',`id=eq.${encodeURIComponent(id)}`);await refresh(undefined,row.slug);redirect('/admin/dijital-markalar')}
export async function addDigitalBrandLinkAction(f:FormData){await requireAdmin();const pageId=text(f,'page_id'),label=text(f,'label'),href=text(f,'href');if(!pageId||!label||!href)throw new Error('Bağlantı adı ve adresi gerekli.');await insert('digital_brand_links',{page_id:pageId,label,href,note:text(f,'note')||null,icon:text(f,'icon')||null,featured:yes(f,'featured'),active:true,sort_order:Number(text(f,'sort_order')||0)});const row=(await select<{slug:string}>('digital_brand_pages',`id=eq.${encodeURIComponent(pageId)}&select=slug&limit=1`))[0];await refresh(pageId,row?.slug)}
export async function updateDigitalBrandLinkAction(f:FormData){await requireAdmin();const id=text(f,'id'),pageId=text(f,'page_id');await update('digital_brand_links',`id=eq.${encodeURIComponent(id)}&page_id=eq.${encodeURIComponent(pageId)}`,{label:text(f,'label'),href:text(f,'href'),note:text(f,'note')||null,icon:text(f,'icon')||null,featured:yes(f,'featured'),active:yes(f,'active'),sort_order:Number(text(f,'sort_order')||0),updated_at:new Date().toISOString()});const row=(await select<{slug:string}>('digital_brand_pages',`id=eq.${encodeURIComponent(pageId)}&select=slug&limit=1`))[0];await refresh(pageId,row?.slug)}
export async function deleteDigitalBrandLinkAction(f:FormData){await requireAdmin();const id=text(f,'id'),pageId=text(f,'page_id');await remove('digital_brand_links',`id=eq.${encodeURIComponent(id)}&page_id=eq.${encodeURIComponent(pageId)}`);const row=(await select<{slug:string}>('digital_brand_pages',`id=eq.${encodeURIComponent(pageId)}&select=slug&limit=1`))[0];await refresh(pageId,row?.slug)}
